"""Build one deployable wheel per model, scoped to what that job actually needs.

Problem this solves: ``[tool.setuptools] packages`` in the repo's own
``pyproject.toml`` bundles ``shared``, ``app``, ``job`` *and all of*
``models`` into a single wheel. A model's own dependencies are already
scoped correctly via ``pyproject.toml``'s per-model extras (``gurobi``,
``forecasting``, ``mcmc``, ``scenario``, ``streaming``) — but the *source*
of every model still ships to every job's deployment regardless of which
one it runs, because ``job/loader.py`` only chooses what to *import* at
runtime, after everything is already on disk.

This script stages ``shared/`` + ``job/`` + exactly one ``models/<name>/``
into a throwaway directory with a small generated ``pyproject.toml``, and
builds a wheel from that — nothing else. The MCMC job's wheel ends up with
``shared``, ``job``, ``models.mcmc``, and MCMC's own dependencies. No
sibling model source, no sibling model dependencies.

Usage::

    uv run python scripts/build_model_wheel.py mcmc
    uv run python scripts/build_model_wheel.py --all
    uv run python scripts/build_model_wheel.py scenario forecasting -o build/wheels/

Requires ``uv`` on PATH (already the project's build/dependency tool —
see ``CLAUDE.md``, "uv, and the lockfile is the source of truth").

Note on the Delta writer: ``deltalake``/``pyarrow`` are **excluded by
default**. ``job/delta.py``'s ``DeltaRsWriter`` raises ``NotImplementedError``
(it cannot address a Unity Catalog table by name and writes to a local
directory instead of failing), so Spark is the write path and those two
packages would otherwise ship to every job to satisfy an import that never
runs. ``--with-delta`` is there for the change that makes delta-rs real.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _registry import UnregisteredModel, extra_for, model_names  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent

#: The model registry lives in pyproject.toml's [tool.dbx-leaning.models],
#: read through scripts/_registry.py — this script and the requirements
#: exporter used to keep separate copies of the same map, which is a
#: divergence waiting to deploy the wrong dependencies.


#: Nested subpackages that must be listed explicitly for setuptools' literal
#: ``packages`` list (it does not auto-discover subpackages the way
#: ``find_packages()`` would). Keep in sync with what actually exists under
#: job/ — this is intentionally hand-maintained, not auto-walked, so an
#: added subpackage is a visible, deliberate change here too.
JOB_SUBPACKAGES: tuple[str, ...] = ("job.drivers",)


class BuildError(RuntimeError):
    pass


def load_root_pyproject() -> dict:
    path = REPO_ROOT / "pyproject.toml"
    with path.open("rb") as f:
        return tomllib.load(f)


def _dedup(items: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if item not in seen:
            seen.add(item)
            out.append(item)
    return out


def resolve_dependencies(root: dict, *, model_extra: str, include_delta: bool) -> list[str]:
    project = root["project"]
    optional = project.get("optional-dependencies", {})

    core = list(project.get("dependencies", []))
    job = list(optional.get("job", []))
    delta = list(optional.get("delta", [])) if include_delta else []
    try:
        model = list(optional[model_extra])
    except KeyError:
        raise BuildError(
            f"pyproject.toml has no [project.optional-dependencies].{model_extra!r} "
            f"extra; available: {sorted(optional)}"
        ) from None

    return _dedup(core + job + delta + model)


def render_pyproject(
    *,
    name: str,
    version: str,
    requires_python: str,
    build_system: dict,
    dependencies: list[str],
    packages: list[str],
) -> str:
    deps_toml = ",\n".join(f'    "{d}"' for d in dependencies)
    packages_toml = ", ".join(f'"{p}"' for p in packages)
    requires_toml = ", ".join(f'"{r}"' for r in build_system.get("requires", ["setuptools>=68"]))
    backend = build_system.get("build-backend", "setuptools.build_meta")

    return f"""\
[build-system]
requires = [{requires_toml}]
build-backend = "{backend}"

[project]
name = "{name}"
version = "{version}"
description = "Scoped deployment wheel — generated by scripts/build_model_wheel.py, do not edit"
requires-python = "{requires_python}"
dependencies = [
{deps_toml}
]

[tool.setuptools]
packages = [{packages_toml}]
"""


def stage_and_build(
    model_dir_name: str,
    *,
    out_dir: Path,
    include_delta: bool = False,
    keep_tmp: bool = False,
) -> Path:
    root = load_root_pyproject()
    project = root["project"]

    src_model_path = REPO_ROOT / "models" / model_dir_name
    if not src_model_path.is_dir():
        raise BuildError(
            f"models/{model_dir_name} does not exist (looked under {REPO_ROOT / 'models'})"
        )
    try:
        extra = extra_for(model_dir_name)
    except UnregisteredModel as exc:
        raise BuildError(str(exc)) from None
    dependencies = resolve_dependencies(root, model_extra=extra, include_delta=include_delta)

    stage = REPO_ROOT / ".build" / f"wheel-{model_dir_name}"
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir(parents=True)

    try:
        # shared/ and job/ verbatim; models/<name>/ only, plus a bare
        # models/__init__.py so "models" is still a regular package without
        # dragging in any sibling model.
        shutil.copytree(REPO_ROOT / "shared", stage / "shared")
        shutil.copytree(REPO_ROOT / "job", stage / "job")
        (stage / "models").mkdir()
        shutil.copy2(REPO_ROOT / "models" / "__init__.py", stage / "models" / "__init__.py")
        shutil.copytree(src_model_path, stage / "models" / model_dir_name)

        packages = ["shared", "job", *JOB_SUBPACKAGES, "models", f"models.{model_dir_name}"]
        pyproject_text = render_pyproject(
            name=f"{project['name']}-{model_dir_name.replace('_', '-')}",
            version=project["version"],
            requires_python=project["requires-python"],
            build_system=root["build-system"],
            dependencies=dependencies,
            packages=packages,
        )
        (stage / "pyproject.toml").write_text(pyproject_text)

        model_out = out_dir / model_dir_name
        model_out.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            ["uv", "build", "--wheel", str(stage), "-o", str(model_out)],
            check=True,
        )
        return model_out
    finally:
        if not keep_tmp:
            shutil.rmtree(stage, ignore_errors=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "models", nargs="*", help="model directory names under models/, e.g. mcmc scenario"
    )
    parser.add_argument("--all", action="store_true", help="build every model under models/")
    parser.add_argument(
        # NOT `dist`: that name at the repo root is the built SPA now, and it
        # is tracked (see app/client/.gitignore). Wheels go under `build/`,
        # which .gitignore already covers.
        "-o",
        "--out-dir",
        default="build/wheels",
        type=Path,
        help="output root (default: build/wheels/)",
    )
    parser.add_argument(
        "--with-delta",
        action="store_true",
        help="include the delta-rs extra (deltalake/pyarrow). OFF by default: "
        "job/delta.py's DeltaRsWriter raises NotImplementedError, so those two "
        "packages would ship to every job to satisfy an import that never runs. "
        "Turn this on in the same change that makes delta-rs real.",
    )
    parser.add_argument(
        "--keep-tmp",
        action="store_true",
        help="leave the staged .build/wheel-<model>/ directory for inspection",
    )
    args = parser.parse_args(argv)

    if args.all:
        targets = model_names()
    elif args.models:
        targets = args.models
    else:
        parser.error("give one or more model names, or pass --all")
        return 2  # pragma: no cover - argparse exits before this

    if shutil.which("uv") is None:
        print("error: uv is not on PATH — see CLAUDE.md, this repo builds with uv", file=sys.stderr)
        return 1

    failures: list[str] = []
    for name in targets:
        print(f"--- building {name} ---")
        try:
            out = stage_and_build(
                name, out_dir=args.out_dir, include_delta=args.with_delta, keep_tmp=args.keep_tmp
            )
        except BuildError as exc:
            print(f"error: {exc}", file=sys.stderr)
            failures.append(name)
            continue
        except subprocess.CalledProcessError:
            print(f"error: uv build failed for {name}", file=sys.stderr)
            failures.append(name)
            continue
        built = sorted(out.glob("*.whl"))
        for whl in built:
            print(f"  built {whl}")

    if failures:
        print(f"failed: {', '.join(failures)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
